"""Dev: payroll scale

Revision ID: 20ad1d929040
Revises: eabcb4e7f5ae
Create Date: 2020-08-21 18:27:50.341991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20ad1d929040'
down_revision = 'eabcb4e7f5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client_groups', ['id'])
    op.create_unique_constraint(None, 'clients', ['name'])
    op.create_unique_constraint(None, 'payroll_files', ['name'])
    op.drop_index('ix_payrolls_salary_grade_id', table_name='payrolls')
    op.drop_index('ix_payrolls_salary_step_id', table_name='payrolls')
    op.drop_constraint('payrolls_ibfk_3', 'payrolls', type_='foreignkey')
    op.drop_constraint('payrolls_ibfk_1', 'payrolls', type_='foreignkey')
    op.drop_constraint('payrolls_ibfk_2', 'payrolls', type_='foreignkey')
    op.drop_column('payrolls', 'ippis_id')
    op.drop_column('payrolls', 'department_id')
    op.drop_column('payrolls', 'salary_structure_id')
    op.drop_column('payrolls', 'employee_id')
    op.drop_column('payrolls', 'user_id')
    op.drop_column('payrolls', 'service_id')
    op.drop_column('payrolls', 'salary_grade_id')
    op.drop_column('payrolls', 'salary_step_id')
    op.drop_column('payrolls', 'pension_provider_id')
    op.drop_column('payrolls', 'designation_id')
    op.drop_column('payrolls', 'bank_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('bank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('designation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('pension_provider_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('salary_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('salary_grade_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('salary_structure_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('payrolls', sa.Column('ippis_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('payrolls_ibfk_2', 'payrolls', 'salary_grades', ['salary_grade_id'], ['id'])
    op.create_foreign_key('payrolls_ibfk_1', 'payrolls', 'salary_structures', ['salary_structure_id'], ['id'])
    op.create_foreign_key('payrolls_ibfk_3', 'payrolls', 'salary_steps', ['salary_step_id'], ['id'])
    op.create_index('ix_payrolls_salary_step_id', 'payrolls', ['salary_step_id'], unique=False)
    op.create_index('ix_payrolls_salary_grade_id', 'payrolls', ['salary_grade_id'], unique=False)
    op.drop_constraint(None, 'payroll_files', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'client_groups', type_='unique')
    # ### end Alembic commands ###
