"""Initial migration.

Revision ID: eabcb4e7f5ae
Revises: 
Create Date: 2020-08-21 03:18:08.363066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabcb4e7f5ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_groups', sa.Column('description', sa.String(length=700), nullable=True))
    op.add_column('client_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('note', sa.String(length=700), nullable=True))
    op.add_column('contact_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('payroll_files', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('payrolls', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'is_active')
    op.drop_column('payroll_files', 'is_active')
    op.drop_column('contacts', 'is_active')
    op.drop_column('contact_groups', 'is_active')
    op.drop_column('clients', 'note')
    op.drop_column('clients', 'is_active')
    op.drop_column('client_groups', 'is_active')
    op.drop_column('client_groups', 'description')
    # ### end Alembic commands ###
